### ISSUE TITLE
Fails to build on Gentoo

### ISSUE THREAD

**Issue by bemeurer** [sifive/freedom-e-sdk#108]
Trying to issue `make tools` on Gentoo fails while compiling GCC. Here's the [build log](https://ptpb.pw/pq3B). The failures seem to be happening while building the graphite polyhedral optimizer. I am on GCC 7.3.0.

**Comment by jim-wilson** [comment]
Looks like
    https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86724
which is a versioning problem with the isl library that has a simple solution.

I also see gdb build failures with guile, which is another versioning problem.  The recommended solution for this is to just disable guile support in gdb, since almost no one needs it.  You can do this by specifying "--with-guile=no" when configuring riscv-gnu-toolchain.  You can modify the top level Makefile to pass the extra option when configuring riscv-gnu-toolchain.

**Comment by bemeurer** [comment]
@jim-wilson Success!

After applying the patch, and disabling guile it has successfully compiled

Thank you!
